//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaSeguros.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolizasDBEntities : DbContext
    {
        public PolizasDBEntities()
            : base("name=PolizasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cubrimiento> Cubrimiento { get; set; }
        public virtual DbSet<Poliza> Poliza { get; set; }
        public virtual DbSet<PolizaCoberturas> PolizaCoberturas { get; set; }
        public virtual DbSet<Riesgo> Riesgo { get; set; }
    }
}
